INSERT INTO DBSYS01.USER_MGMT (USER_NAME, USER_PASSWORD, USER_ROLE) 
	VALUES ('apatel', '$2a$08$cOCM1U124gIRButx5mJsNeRqlrckwEfs9JXG7KQ2myglq2Z7RVdca', 'ADMIN'),
			('atul', '$2a$08$h2A3t86jIErAO54gYyUu4eF4A/4WTeZClSRaew4cGkiiCiFiGQtO6', 'NORMAL');
            
INSERT INTO DBSYS01.USER_MGMT (USER_NAME, USER_PASSWORD, USER_ROLE) 
	VALUES  ('admin', '$2a$08$uPtLLuqatph51g45cI4vVeP5dTz0CdOAdJVfv7BS2bwAQ2xjl/Gya', 'ADMIN'),
			('user', '$2a$08$/65XmTOeNIXUOObatgsaT.48fz.haDcrQxj5BwJpEPTHDHscndQZ6', 'NORMAL');
            
SELECT * FROM DBSYS01.USER_MGMT;

delete from DBSYS01.USER_MGMT WHERE USER_NAME IN ("admin","user");