CREATE DATABASE IF NOT EXISTS DBSYS01;

CREATE TABLE IF NOT EXISTS DBSYS01.USER_MGMT (
    USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_NAME VARCHAR(255) NOT NULL UNIQUE,
    USER_PASSWORD VARCHAR(255) NOT NULL,
    USER_ROLE VARCHAR(255) NOT NULL
);

DROP TABLE DBSYS01.USER_MGMT;

CREATE TABLE IF NOT EXISTS DBSYS01.COURSE_MGMT (
    COURSE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    COURSE_NAME VARCHAR(255) NOT NULL UNIQUE,
    COURSE_ASSIGNEE VARCHAR(50) NULL,
    COURSE_STATUS VARCHAR(50) NOT NULL
);