spring.application.name=my-project-spring-boot-a

#To Enable/Disable the Debug mode
#logging.level.org.springframework=DEBUG

#To enable all the end-points
#management.endpoints.web.exposure.include=*

#To enable only specific & required end-points
management.endpoints.web.exposure.include=health,metrics