spring.application.name=cards-one-stop-shop

# API Context Path
server.servlet.context-path=/cards-one-stop-shop

# MySQL DataSource
spring.datasource.url=jdbc:mysql://localhost:3306/DBSYS01?useSSL=false&serverTimezone=UCT
spring.datasource.username=root
spring.datasource.password=Pass@RooT1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Thymeleaf
spring.thymeleaf.cache=false
