spring.application.name=my-rest-api-course

#Enable H2 Console
spring.h2.console.enabled=true

#Define a static URL for H2 DB
spring.datasource.url=jdbc:h2:mem:testdb

#To see the SQL being executed by JPA
spring.jpa.show-sql=true

spring.jpa.defer-datasource-initialization=true
