INSERT INTO COURSE(ID, NAME, AUTHOR) 
VALUES 	 (100102,'PYTHON FUNDAMENTALS VI','PAUL JONES VI');

INSERT INTO COURSE(ID, NAME, AUTHOR) 
VALUES 	 (100103,'AWS Fundamentals','Amazon');

INSERT INTO COURSE(ID, NAME, AUTHOR) 
VALUES 	 (100104,'Azure AZ-600','Microsoft');

INSERT INTO COURSE(ID, NAME, AUTHOR) 
VALUES 	 (100105,'GCP','Google');